### PR TITLE
Add models file to start project generator

### PR DESCRIPTION
**Pull request by e0**
#5

### CODE REVIEW

**Comment by lohmander** [comment]
I don't think the model should actually be defined though. What if the user runs sync db right away? Then he or she would have an unwanted table in the database. How about just having a comment with

```python
# Create your models here. Documentation can be found here: 
# https://brinkframework.github.io/brink/models.html
```

**Comment by e0** [comment]
The model included in the pull request is commented out. Only the two imports of Model and fields are actual code so I don't think sync-db would trigger anything. But do you think we should omit the imports as well?

I do think that your suggestion for comment is good though.

**Comment by lohmander** [comment]
Right sorry, didn't see that. It's a doc comment so probably not appropriate for this purpose, use `#` instead in that case. But again I vote for just referencing the docs.

**Comment by lohmander** [comment]
@e0 please fix this if you want me to merge the PR.

**Comment by e0** [comment]
I will close this, and make a new PR since I have push access now.

**Pull request closed without merging**
